<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends User_Controller{
    function __construct()
    {
        parent::__construct();
        

         /* Title Page :: Common */
         $this->page_title->push('Dashboard');
         $this->data['pagetitle'] = $this->page_title->show();
 
         /* Breadcrumbs :: Common */
         $this->breadcrumbs->unshift(1, 'Dashboard', 'Dashboard');
    } 

    /*
     * Listing of interview_evaluation
     */
    function index()
    {
        $this->template->public_render('Dashboard/index', $this->data);
    }
}