<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Department extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Department_model');
         /* Title Page :: Common */
         $this->page_title->push('Department');
         $this->data['pagetitle'] = $this->page_title->show();
 
         /* Breadcrumbs :: Common */
         $this->breadcrumbs->unshift(1, 'Department', 'Department');
    } 

    /*
     * Listing of department
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('Department/index?');
        $config['total_rows'] = $this->Department_model->get_all_department_count();
        $this->pagination->initialize($config);
        /* Breadcrumbs */
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['department'] = $this->Department_model->get_all_department($params);
        
        $this->template->public_render('Department/index', $this->data);

   
    }

    /*
     * Adding a new department
     */
    function add()
    {   
        $this->breadcrumbs->unshift(2, 'Add', 'add');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $department_id = $this->Department_model->add_department($params);
            redirect('Department/index');
        }
        else
        {      
            $this->template->public_render('Department/add', $this->data);      
           
        }
    }  

    /*
     * Editing a department
     */
    function edit($id)
    {   
        $this->breadcrumbs->unshift(2, 'Edit', 'edit');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        // check if the department exists before trying to edit it
        $this->data['department'] = $this->Department_model->get_department($id);
        
        if(isset($this->data['department']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Department_model->update_department($id,$params);            
                redirect('Department/index');
            }
            else
            {
                $this->template->public_render('Department/edit', $this->data); 
            }
        }
        else
            show_error('The department you are trying to edit does not exist.');
    } 

    /*
     * Deleting department
     */
    function remove($id)
    {
        $department = $this->Department_model->get_department($id);

        // check if the department exists before trying to delete it
        if(isset($department['id']))
        {
            $this->Department_model->delete_department($id);
            redirect('Department/index');
        }
        else
            show_error('The department you are trying to delete does not exist.');
    }
    
}
