<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Designation extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Designation_model');

        /* Title Page :: Common */
        $this->page_title->push('Designation');
        $this->data['pagetitle'] = $this->page_title->show();

        /* Breadcrumbs :: Common */
        $this->breadcrumbs->unshift(1, 'Designation', 'Designation');
    } 

    /*
     * Listing of designation
     */
    function index()
    {
       
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['designation'] = $this->Designation_model->get_all_designation();
        $this->template->public_render('Designation/index', $this->data);
        
    }

    /*
     * Adding a new designation
     */
    function add()
    {   
        $this->breadcrumbs->unshift(2, 'Designation', 'Designation/add');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $designation_id = $this->Designation_model->add_designation($params);
            redirect('Designation/index');
        }
        else
        {            
            $this->template->public_render('Designation/add', $this->data);
        }
    }  

    /*
     * Editing a designation
     */
    function edit($id)
    {   
        $this->breadcrumbs->unshift(2, 'Designation', 'Designation/Edit');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        // check if the designation exists before trying to edit it
        $this->data['designation'] = $this->Designation_model->get_designation($id);
        
        if(isset($this->data['designation']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Designation_model->update_designation($id,$params);            
                redirect('Designation/index');
            }
            else
            {
                $this->template->public_render('Designation/edit', $this->data);
            }
        }
        else
            show_error('The designation you are trying to edit does not exist.');
    } 

    /*
     * Deleting designation
     */
    function remove($id)
    {
        $designation = $this->Designation_model->get_designation($id);

        // check if the designation exists before trying to delete it
        if(isset($designation['id']))
        {
            $this->Designation_model->delete_designation($id);
            redirect('Designation/index');
        }
        else
            show_error('The designation you are trying to delete does not exist.');
    }
    
}
