<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_termination extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_termination_model');
        $this->load->model('Employees_model');
        /* Title Page :: Common */
        $this->page_title->push('Termination');
        $this->data['pagetitle'] = $this->page_title->show();

        /* Breadcrumbs :: Common */
        $this->breadcrumbs->unshift(1, 'Resign', 'Employee_termination');
    } 

    /*
     * Listing of employee_termination
     */
    function index()
    {
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['employee_termination'] = $this->Employee_termination_model->get_all_employee_termination();
        $this->template->public_render('employee_termination/index', $this->data);
    }

    /*
     * Adding a new employee_termination
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('employee_id','Employee Name','required');
        $this->form_validation->set_rules('termination_date','Termination Date','required');
        $this->form_validation->set_rules('termination_reason','Reason','required');
        if($this->form_validation->run())     
        {   
            $params = array(
				'employee_id' => $this->input->post('employee_id'),
				'termination_date' => date("Y-m-d",strtotime($this->input->post('termination_date'))),
                'termination_reason' => $this->input->post('termination_reason'),
                'created_at' => date('Y-m-d'),
            );
            
            $employee_termination_id = $this->Employee_termination_model->add_employee_termination($params);
            redirect('Employee_termination/index');
        }
        else
        {        
            $this->breadcrumbs->unshift(2, 'create', 'employee_termination/add');
            $this->data['breadcrumb'] = $this->breadcrumbs->show();
            $this->data['employee'] = $this->Employees_model->get_all_employee();       
            $this->template->public_render('employee_termination/add', $this->data);
            
        }
    }  

    /*
     * Editing a employee_termination
     */
    function edit($id)
    {   
        // check if the employee_termination exists before trying to edit it
        $this->data['employee_termination'] = $this->Employee_termination_model->get_employee_termination($id);
        
        if(isset($this->data['employee_termination']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'employee_id' => $this->input->post('employee_id'),
					'termination_date' => date("Y-m-d",strtotime($this->input->post('termination_date'))),
					'termination_reason' => $this->input->post('termination_reason'),
                );

                $this->Employee_termination_model->update_employee_termination($id,$params);            
                redirect('Employee_termination/index');
            }
            else
            {
                $this->breadcrumbs->unshift(2, 'update', 'employee_termination/edit');
                $this->data['breadcrumb'] = $this->breadcrumbs->show();
                $this->data['employee'] = $this->Employees_model->get_all_employee(); 
                $this->template->public_render('employee_termination/edit', $this->data);
            }
        }
        else
            show_error('The employee termination you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee_termination
     */
    function remove($id)
    {
        $employee_termination = $this->Employee_termination_model->get_employee_termination($id);

        // check if the employee_termination exists before trying to delete it
        if(isset($employee_termination['id']))
        {
            $this->Employee_termination_model->delete_employee_termination($id);
            redirect('Employee_termination/index');
        }
        else
            show_error('The employee termination you are trying to delete does not exist.');
    }
    
}
