<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
ini_set('display_errors',1);
class Employee_attendance extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employees_model');
        $this->load->model('Department_model');
        $this->load->model('Designation_model');
		$this->load->model('Employees_attendance_model');
		
         /* Title Page :: Common */
         $this->page_title->push('Employee Attendance Taken');
         $this->data['pagetitle'] = $this->page_title->show();
 
         /* Breadcrumbs :: Common */
         $this->breadcrumbs->unshift(1, 'Attendance', 'attendance');

         $this->load->library('Pdf');
    } 

    /*
     * Listing of Employee
     */
    function index()
    {
        //$params['limit'] = RECORDS_PER_PAGE; 
        //$params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        /* $config = $this->config->item('pagination');
        $config['base_url'] = site_url('Employee/index?');
        $config['total_rows'] = $this->Employees_model->get_all_employee_count();
        $this->pagination->initialize($config); */

        /* Breadcrumbs */
        $this->breadcrumbs->unshift(2, 'Listing', 'attendance');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();

        $this->data['employee'] = $this->Employees_model->get_all_employee();
        /* Load Template */
        $this->template->public_render('Attendance/index', $this->data);
    }
	
	//Get Employees
    function getEmployees(){
		$response=array();
		$num_rec_per_page = $_POST["perpage"];
		if (isset($_POST["page"])) { $page  = $_POST["page"]; } else { $page=1; };
		$start_from = ($page-1) * $num_rec_per_page;
		$response['start_from']=$start_from;
		$employess=$this->Employees_attendance_model->getAllEmployess();
		foreach($employess as $key=>$emp){
			$emp->emp_index=$key;
			$emp->take_attendance=(!empty($emp->ATTENDACE))?$emp->ATTENDACE:'';
			$emp->late=(!empty($emp->IS_LATE))?true:false;
			$emp->location=(!empty($emp->LOCATION))?$emp->LOCATION:'office';
			$emp->sign_in=(!empty($emp->SIGN_IN))?date('H:i A',strtotime($emp->SIGN_IN)):'--';
			$emp->sign_out=(!empty($emp->SIGN_OUT))?date('H:i A',strtotime($emp->SIGN_OUT)):'--';
			$emp->is_done_sign_in=(!empty($emp->SIGN_IN))?true:false;
			$emp->is_done_sign_out=(!empty($emp->SIGN_OUT))?true:false;
		}
		
		$attendance_obj=$this->Employees_attendance_model->checkAttendance();
		$response['employess']=$employess;
		$response['show_action_btn']=(!empty($attendance_obj[0]->total_cnt))?'Update_Attendance':'Take_Attendance';
		$response['total_presents']=(!empty($attendance_obj[0]->total_cnt))?$attendance_obj[0]->total_presents:0;
		$response['total_absents']=(!empty($attendance_obj[0]->total_cnt))?$attendance_obj[0]->total_absents:0;
		echo json_encode($response);
	}
	
	//Save Attendance
	function saveAttendance(){
		$response=$data=array();
		$emps=json_decode($_POST['emps'],true);
		for($i=0;$i<count($emps);$i++){
			$ATTENDANCE_TAKEN_DATE=date('Y-m-d H:i:s');
			$UID=$emps[$i]['id'];
			$ATTENDACE=$emps[$i]['take_attendance'];
			$LOCATION=$emps[$i]['location'];
			$IS_LATE=($emps[$i]['late']==true)?1:0;
			$SIGN_IN=date('Y-m-d H:i:s');
			$data[]=array('ATTENDANCE_TAKEN_DATE'=>$ATTENDANCE_TAKEN_DATE,
						  'UID'=>$UID,
						  'ATTENDACE'=>$ATTENDACE,
						  'LOCATION'=>$LOCATION,
						  'IS_LATE'=>$IS_LATE,
						  'SIGN_IN'=>$SIGN_IN);
		}
		$result=$this->Employees_attendance_model->saveAttendance($data);
		/*if($result>0){
			$response['error']=false;
			$response['message']='Success';
			$response['show_action_btn']='Take_Attendance';
		}else{
			$response['error']=true;
			$response['message']='Fail';
			$response['show_action_btn']='Update_Attendance';
		}*/
		$response['error']=true;
		$response['message']='Fail';
		$response['show_action_btn']='Update_Attendance';
				
		echo json_encode($response);
	}
    
}
