<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_resign extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_resign_model');
        $this->load->model('Employees_model');
        /* Title Page :: Common */
        $this->page_title->push('Resign');
        $this->data['pagetitle'] = $this->page_title->show();

        /* Breadcrumbs :: Common */
        $this->breadcrumbs->unshift(1, 'Resign', 'Employee_resign');
    } 

    /*
     * Listing of employee_resign
     */
    function index()
    {
        
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['employee_resign'] = $this->Employee_resign_model->get_all_employee_resign();
        //$this->data[]
        $this->template->public_render('employee_resign/index', $this->data);
    }

    /*
     * Adding a new employee_resign
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('employee_id','Employee Name','required');
        $this->form_validation->set_rules('resign_date','Resign Date','required');
        $this->form_validation->set_rules('resign_reason','Reason','required');
        if($this->form_validation->run())     
        {   
            $params = array(
				'employee_id' => $this->input->post('employee_id'),
				'resign_date' => date("Y-m-d",strtotime($this->input->post('resign_date'))),
                'resign_reason' => $this->input->post('resign_reason'),
                'created_at' => date('Y-m-d'),
            );
            
            $employee_resign_id = $this->Employee_resign_model->add_employee_resign($params);
            redirect('employee_resign/index');
        }
        else
        {     
            $this->breadcrumbs->unshift(2, 'create', 'employee_resign/add');
            $this->data['breadcrumb'] = $this->breadcrumbs->show();
            $this->data['employee'] = $this->Employees_model->get_all_employee();       
            $this->template->public_render('employee_resign/add', $this->data);
        }
    }  

    /*
     * Editing a employee_resign
     */
    function edit($id)
    {   
        // check if the employee_resign exists before trying to edit it
        $this->data['employee_resign'] = $this->Employee_resign_model->get_employee_resign($id);
        
        if(isset($this->data['employee_resign']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'employee_id' => $this->input->post('employee_id'),
					'resign_date' => date("Y-m-d",strtotime($this->input->post('resign_date'))),
					'resign_reason' => $this->input->post('resign_reason'),
                );

                $this->Employee_resign_model->update_employee_resign($id,$params);            
                redirect('employee_resign/index');
            }
            else
            {
                $this->breadcrumbs->unshift(2, 'update', 'employee_resign/edit');
                $this->data['breadcrumb'] = $this->breadcrumbs->show();
                $this->data['employee'] = $this->Employees_model->get_all_employee(); 
                $this->template->public_render('employee_resign/edit', $this->data);
            }
        }
        else
            show_error('The employee resign you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee_resign
     */
    function remove($id)
    {
        $employee_resign = $this->Employee_resign_model->get_employee_resign($id);

        // check if the employee_resign exists before trying to delete it
        if(isset($employee_resign['id']))
        {
            $this->Employee_resign_model->delete_employee_resign($id);
            redirect('employee_resign/index');
        }
        else
            show_error('The employee resign you are trying to delete does not exist.');
    }
    
}
