<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_appriasal extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_appriasal_model');
        $this->load->model('Employees_model');
        $this->load->model('Department_model');
        $this->load->model('Designation_model');
        /* Title Page :: Common */
        $this->page_title->push('Appriasal');
        $this->data['pagetitle'] = $this->page_title->show();

        /* Breadcrumbs :: Common */
        $this->breadcrumbs->unshift(1, 'Employee', 'Employee');
    } 

    /*
     * Listing of employee_appriasal
     */
    function index()
    {
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['employee_appriasal'] = $this->Employee_appriasal_model->get_all_employee_appriasal();
        $this->template->public_render('employee_appriasal/index', $this->data);
        
    }

    /*
     * Adding a new employee_appriasal
     */
    function add($id)
    {          

        $this->form_validation->set_rules('review_fre','Review Period','required');
        $this->form_validation->set_rules('present_rate','Present Rate','required');
        $this->form_validation->set_rules('review_date','Date of Review','required');

        if($this->form_validation->run())     
        {  
            $params = array(
				'empId' => $this->input->post('empId'),
                'created_at' => date('Y-m-d'),
                'present_rate' => $this->input->post('present_rate'),
                'review_date' => date('Y-m-d',strtotime($this->input->post('review_date'))),
				'review_fre' => $this->input->post('review_fre'),
				'attendance' => $this->input->post('attendance'),
				'quality_work' => $this->input->post('quality_work'),
				'productivity' => $this->input->post('productivity'),
				'kldg_job' => $this->input->post('kldg_job'),
				'randa' => $this->input->post('randa'),
				'initiative' => $this->input->post('initiative'),
				'creativity' => $this->input->post('creativity'),
				'work_rela' => $this->input->post('work_rela'),
				'adherence' => $this->input->post('adherence'),
				'org_perform' => $this->input->post('org_perform'),
				'overall' => $this->input->post('overall'),
				'att_com' => $this->input->post('att_com'),
				'qow_com' => $this->input->post('qow_com'),
				'prod_com' => $this->input->post('prod_com'),
				'kldg_com' => $this->input->post('kldg_com'),
				'randa_com' => $this->input->post('randa_com'),
				'init_com' => $this->input->post('init_com'),
				'creat_com' => $this->input->post('creat_com'),
				'workrela_com' => $this->input->post('workrela_com'),
				'adherence_com' => $this->input->post('adherence_com'),
				'org_com' => $this->input->post('org_com'),
				'overall_com' => $this->input->post('overall_com'),
				'sprv_com' => $this->input->post('sprv_com'),
				'emp_com' => $this->input->post('emp_com'),
				'emp_improve' => $this->input->post('emp_improve'),
            );
           // print_r($params); 
            $employee_appriasal_id = $this->Employee_appriasal_model->add_employee_appriasal($params);
            redirect('Employee_appriasal/index');
        }
        else
        {    
            $this->data['employee'] = $this->Employees_model->get_employee($id);
            
            $department = $this->Department_model->get_department($this->data['employee']['Department']);
            $this->data['employee']['Department'] =$department['name'];

            $designation = $this->Designation_model->get_designation($this->data['employee']['Designation']);
            $this->data['employee']['Designation'] =$designation['name'];
            
            $this->template->public_render('employee_appriasal/add', $this->data);        
        }
    }  

    /*
     * Editing a employee_appriasal
     */
    function edit($id)
    {   
       
        // check if the employee_appriasal exists before trying to edit it
         $this->data['employee_appriasal'] = $this->Employee_appriasal_model->get_employee_appriasal($id);
         $this->data['employee'] = $this->Employees_model->get_employee_empid($this->data['employee_appriasal']['empId']);
        // print_r($this->data['employee']); exit;
        $department = $this->Department_model->get_department($this->data['employee']['Department']);
        $this->data['employee']['Department'] =$department['name'];
        
        $designation = $this->Designation_model->get_designation($this->data['employee']['Designation']);
        $this->data['employee']['Designation'] =$designation['name'];
       //
        if(isset( $this->data['employee_appriasal']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'empId' => $this->input->post('empId'),
                    'created_at' => date('Y-m-d'),
                    'present_rate' => $this->input->post('present_rate'),
                    'review_date' => date('Y-m-d',strtotime($this->input->post('review_date'))),
                    'review_fre' => $this->input->post('review_fre'),
                    'attendance' => $this->input->post('attendance'),
                    'quality_work' => $this->input->post('quality_work'),
                    'productivity' => $this->input->post('productivity'),
                    'kldg_job' => $this->input->post('kldg_job'),
                    'randa' => $this->input->post('randa'),
                    'initiative' => $this->input->post('initiative'),
                    'creativity' => $this->input->post('creativity'),
                    'work_rela' => $this->input->post('work_rela'),
                    'adherence' => $this->input->post('adherence'),
                    'org_perform' => $this->input->post('org_perform'),
                    'overall' => $this->input->post('overall'),
                    'att_com' => $this->input->post('att_com'),
                    'qow_com' => $this->input->post('qow_com'),
                    'prod_com' => $this->input->post('prod_com'),
                    'kldg_com' => $this->input->post('kldg_com'),
                    'randa_com' => $this->input->post('randa_com'),
                    'init_com' => $this->input->post('init_com'),
                    'creat_com' => $this->input->post('creat_com'),
                    'workrela_com' => $this->input->post('workrela_com'),
                    'adherence_com' => $this->input->post('adherence_com'),
                    'org_com' => $this->input->post('org_com'),
                    'overall_com' => $this->input->post('overall_com'),
                    'sprv_com' => $this->input->post('sprv_com'),
                    'emp_com' => $this->input->post('emp_com'),
                    'emp_improve' => $this->input->post('emp_improve'),
                );

                $this->Employee_appriasal_model->update_employee_appriasal($id,$params);            
                redirect('Employee_appriasal/index');
            }
            else
            {
                $this->template->public_render('employee_appriasal/edit', $this->data); 
            }
        }
        else
            show_error('The employee_appriasal you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee_appriasal
     */
    function remove($id)
    {
        $employee_appriasal = $this->Employee_appriasal_model->get_employee_appriasal($id);

        // check if the employee_appriasal exists before trying to delete it
        if(isset($employee_appriasal['id']))
        {
            $this->Employee_appriasal_model->delete_employee_appriasal($id);
            redirect('employee_appriasal/index');
        }
        else
            show_error('The employee_appriasal you are trying to delete does not exist.');
    }
    
}
