<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Holiday extends User_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Holiday_model');
        /* Title Page :: Common */
        $this->page_title->push('Holiday');
        $this->data['pagetitle'] = $this->page_title->show();

        /* Breadcrumbs :: Common */
        $this->breadcrumbs->unshift(1, 'Holiday', 'holiday');
    } 

    /*
     * Listing of holidays
     */
    function index()
    {
        $this->breadcrumbs->unshift(2, 'Listing', 'holiday');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
         $this->data['holidays'] = $this->Holiday_model->get_all_holidays();
        /* Load Template */
        $this->template->public_render('holiday/index', $this->data);
        
    }

    /*
     * Adding a new holiday
     */
    function add()
    {   
        $this->breadcrumbs->unshift(2, 'Add', 'holiday');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		$this->form_validation->set_rules('holiday_date','Holiday Date','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'holiday_date' => date("Y-m-d",strtotime($this->input->post('holiday_date'))),
            );
            
            $holiday_id = $this->Holiday_model->add_holiday($params);
            redirect('holiday');
        }
        else
        {            
            /* Load Template */
            $this->template->public_render('holiday/add', $this->data);
        }
    }  

    /*
     * Editing a holiday
     */
    function edit($id)
    {   
        $this->breadcrumbs->unshift(2, 'Edit', 'holiday');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        // check if the holiday exists before trying to edit it
         $this->data['holiday'] = $this->Holiday_model->get_holiday($id);
        
        if(isset( $this->data['holiday']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('holiday_date','Holiday Date','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'holiday_date' => date("Y-m-d",strtotime($this->input->post('holiday_date'))),
                );

                $this->Holiday_model->update_holiday($id,$params);            
                redirect('holiday');
            }
            else
            {
                /* Load Template */
                $this->template->public_render('holiday/edit', $this->data);
            }
        }
        else
            show_error('The holiday you are trying to edit does not exist.');
    } 

    /*
     * Deleting holiday
     */
    function remove($id)
    {
        $holiday = $this->Holiday_model->get_holiday($id);

        // check if the holiday exists before trying to delete it
        if(isset($holiday['id']))
        {
            $this->Holiday_model->delete_holiday($id);
            redirect('holiday');
        }
        else
            show_error('The holiday you are trying to delete does not exist.');
    }
    
}
