<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class MaterialCategory extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('MaterialCategory_model');
         /* Title Page :: Common */
         $this->page_title->push('MaterialCategory');
         $this->data['pagetitle'] = $this->page_title->show();
 
         /* Breadcrumbs :: Common */
         $this->breadcrumbs->unshift(1, 'MaterialCategory', 'MaterialCategory');
    } 

    /*
     * Listing of MaterialCategory
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('MaterialCategory/index?');
        $config['total_rows'] = $this->MaterialCategory_model->get_all_MaterialCategory_count();
        $this->pagination->initialize($config);
        /* Breadcrumbs */
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['MaterialCategory'] = $this->MaterialCategory_model->get_all_MaterialCategory($params);
        
        $this->template->public_render('MaterialCategory/index', $this->data);

   
    }

    /*
     * Adding a new MaterialCategory
     */
    function add()
    {   
        $this->breadcrumbs->unshift(2, 'Add', 'add');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'material_category' => $this->input->post('name'),
            );
            
            $MaterialCategory_id = $this->MaterialCategory_model->add_MaterialCategory($params);
            redirect('MaterialCategory/index');
        }
        else
        {      
            $this->template->public_render('MaterialCategory/add', $this->data);      
           
        }
    }  

    /*
     * Editing a MaterialCategory
     */
    function edit($id)
    {   
        $this->breadcrumbs->unshift(2, 'Edit', 'edit');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        // check if the MaterialCategory exists before trying to edit it
        $this->data['MaterialCategory'] = $this->MaterialCategory_model->get_MaterialCategory($id);
        
        if(isset($this->data['MaterialCategory']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'material_category' => $this->input->post('name'),
                );

                $this->MaterialCategory_model->update_MaterialCategory($id,$params);            
                redirect('MaterialCategory/index');
            }
            else
            {
                $this->template->public_render('MaterialCategory/edit', $this->data); 
            }
        }
        else
            show_error('The MaterialCategory you are trying to edit does not exist.');
    } 

    /*
     * Deleting MaterialCategory
     */
    function remove($id)
    {
        $MaterialCategory = $this->MaterialCategory_model->get_MaterialCategory($id);

        // check if the MaterialCategory exists before trying to delete it
        if(isset($MaterialCategory['id']))
        {
            $this->MaterialCategory_model->delete_MaterialCategory($id);
            redirect('MaterialCategory/index');
        }
        else
            show_error('The MaterialCategory you are trying to delete does not exist.');
    }
    
}
