<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class MaterialSpecification extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('MaterialSpecification_model');
         /* Title Page :: Common */
         $this->page_title->push('MaterialSpecification');
         $this->data['pagetitle'] = $this->page_title->show();
 
         /* Breadcrumbs :: Common */
         $this->breadcrumbs->unshift(1, 'MaterialSpecification', 'MaterialSpecification');
    } 

    /*
     * Listing of MaterialSpecification
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('MaterialSpecification/index?');
        $config['total_rows'] = $this->MaterialSpecification_model->get_all_MaterialSpecification_count();
        $this->pagination->initialize($config);
        /* Breadcrumbs */
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['MaterialSpecification'] = $this->MaterialSpecification_model->get_all_MaterialSpecification($params);

        $this->template->public_render('MaterialSpecification/index', $this->data);

   
    }

    /*
     * Adding a new MaterialSpecification
     */
    function add()
    {   
        $this->breadcrumbs->unshift(2, 'Add', 'add');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');

        // $this->form_validation->set_rules('files','files',count($_FILES['files']['name'])!=0);
        $query = $this->MaterialSpecification_model->select(); 
         $this->data['PROJECTS'] = null;
         if($query){
          $this->data['PROJECTS'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectCat(); 
         $this->data['CATEGORIES'] = null;
         if($query){
          $this->data['CATEGORIES'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectitem(); 
         $this->data['ITEMS'] = null;
         if($query){
          $this->data['ITEMS'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectsupplier(); 
         $this->data['SUPPLIERS'] = null;
         if($query){
          $this->data['SUPPLIERS'] =  $query;
         }
         
         if (empty($_FILES['attach_name']['name']))
        {
            $this->form_validation->set_rules('attach_name', 'Document', 'required');
        }
        $config = array(
            'upload_path' => "./upload/",
            'allowed_types' => "gif|jpg|png|jpeg|pdf",
            'overwrite' => TRUE,
            'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
            'max_height' => "5000",
            'max_width' => "5000"
        );
        $this->load->library('upload', $config);
		if(!empty($_FILES['attach_name']['name']) && $this->upload->do_upload('attach_name'))     
        {   
            $data = $this->input->post();
            $data['material_actual_image'] = $this->upload->data()['file_name'];
            if(!empty($_FILES['attach_name_design']['name']) && $this->upload->do_upload('attach_name_design')){     
            $data['material_design_image'] = $this->upload->data()['file_name'];
            $Design_layout_id = $this->MaterialSpecification_model->add_MaterialSpecification($data);
            redirect('MaterialSpecification/index');}
        }
        else
        {   
            if($this->form_validation->run())
               print_r(' ');
            
            $error = array('error' => $this->upload->display_errors());
            $this->template->public_render('MaterialSpecification/add', $this->data);      
           
        }
    }  

    /*
     * Editing a MaterialSpecification
     */
    function edit($id)
    {
        $this->breadcrumbs->unshift(2, 'Edit', 'edit');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->load->library('form_validation');
        $this->data['MaterialSpecification'] = $this->MaterialSpecification_model->get_MaterialSpecification($id);
        $this->data['MaterialSpecification']['project_name'] = $this->MaterialSpecification_model->get_name($this->data['MaterialSpecification']['project_id']);
        $this->data['MaterialSpecification']['category_name'] = $this->MaterialSpecification_model->get_cat_name($this->data['MaterialSpecification']['material_cat_id']);
        $this->data['MaterialSpecification']['item_name'] = $this->MaterialSpecification_model->get_item_name($this->data['MaterialSpecification']['material_item_id']);
        $this->data['MaterialSpecification']['supplier_name'] = $this->MaterialSpecification_model->get_sup_name($this->data['MaterialSpecification']['supplier_id']);

        // $this->form_validation->set_rules('files','files',count($_FILES['files']['name'])!=0);
        $query = $this->MaterialSpecification_model->select(); 
         $this->data['PROJECTS'] = null;
         if($query){
          $this->data['PROJECTS'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectCat(); 
         $this->data['CATEGORIES'] = null;
         if($query){
          $this->data['CATEGORIES'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectitem(); 
         $this->data['ITEMS'] = null;
         if($query){
          $this->data['ITEMS'] =  $query;
         }
         $query = $this->MaterialSpecification_model->selectsupplier(); 
         $this->data['SUPPLIERS'] = null;
         if($query){
          $this->data['SUPPLIERS'] =  $query;
         }
         if (empty($_FILES['attach_name']['name']))
        {
            $this->form_validation->set_rules('attach_name', 'Document', 'required');
        }
        $config = array(
            'upload_path' => "./upload/",
            'allowed_types' => "gif|jpg|png|jpeg|pdf",
            'overwrite' => TRUE,
            'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
            'max_height' => "5000",
            'max_width' => "5000"
        );
        $this->load->library('upload', $config);
		if(!empty($_FILES['attach_name']['name'])&&$this->upload->do_upload('attach_name'))     
        {   
            $data = $this->input->post();
            $data['updated_at'] = date("Y-m-d H:i:s");
            // print_r($data);
            $data['material_actual_image'] = $this->upload->data()['file_name'];
            if(!empty($_FILES['attach_name_design']['name']) && $this->upload->do_upload('attach_name_design')){     
                $data['material_design_image'] = $this->upload->data()['file_name'];
            $Design_layout_id = $this->MaterialSpecification_model->update_MaterialSpecification($id,$data);
            redirect('MaterialSpecification/index');}
        }
        else
        {   
           
            
            $error = array('error' => $this->upload->display_errors());
            $this->template->public_render('MaterialSpecification/edit', $this->data);      
           
        }
    }

    function image_view($id) {

        $this->breadcrumbs->unshift(2, 'Image View', 'image view');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['MaterialSpecification'] = $this->MaterialSpecification_model->get_MaterialSpecification($id);
        $this->data['imagepath'] = "upload/".$this->data['MaterialSpecification']['material_actual_image'];
        $this->data['id'] = $id;
        $this->template->public_render('MaterialSpecification/image_view', $this->data);

    }
    function image_view1($id) {

        $this->breadcrumbs->unshift(2, 'Image View', 'image view');
        $this->data['breadcrumb'] = $this->breadcrumbs->show();
        $this->data['MaterialSpecification'] = $this->MaterialSpecification_model->get_MaterialSpecification($id);

        $this->data['imagepath'] = "upload/".$this->data['MaterialSpecification']['material_design_image'];
        $this->data['id'] = $id;
        $this->template->public_render('MaterialSpecification/image_view', $this->data);

    }
    /*
     * Deleting MaterialSpecification
     */
    function remove($id)
    {
        $MaterialSpecification = $this->MaterialSpecification_model->get_MaterialSpecification($id);

        // check if the MaterialSpecification exists before trying to delete it
        if(isset($MaterialSpecification['id']))
        {
            $this->MaterialSpecification_model->delete_MaterialSpecification($id);
            redirect('MaterialSpecification/index');
        }
        else
            show_error('The MaterialSpecification you are trying to delete does not exist.');
    }
    function update_remarks($id) {
        $this->MaterialSpecification_model->update_SiteVisitPic($id,$this->input->post());            
        redirect('MaterialSpecification/index');

    }
    
}
