<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_items_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get Account_items by id
     */
    function get_Account_items($id)
    {
        return $this->db->get_where('act_items',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all Account_items count
     */
    function get_all_Account_items_count()
    {
        $this->db->where('delete_status','0');
        $this->db->from('act_items');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all Account_items
     */
    function get_all_Account_items($params = array())
    {
        $this->db->where('delete_status','0');
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('act_items')->result_array();
    }
        
    /*
     * function to add new Account_items
     */
    function add_Account_items($params)
    {
        $this->db->insert('act_items',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Account_items
     */
    function update_Account_items($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_items',$params);
    }
    
    /*
     * function to delete Account_items
     */
    function delete_Account_items($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_items',$params);
    }
}
