<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_cao_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get Account_cao_category by id
     */
    function get_Account_cao_category($id)
    {
        return $this->db->get_where('act_cao_category',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all Account_cao_category count
     */
    function get_all_Account_cao_category_count()
    {
        $this->db->where('delete_status','0');
        $this->db->from('act_cao_category');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all Account_cao_category
     */
    function get_all_Account_cao_category($params = array())
    {
        $this->db->where('delete_status','0');
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('act_cao_category')->result_array();
    }
        
    /*
     * function to add new Account_cao_category
     */
    function add_Account_cao_category($params)
    {
        $this->db->insert('act_cao_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Account_cao_category
     */
    function update_Account_cao_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_cao_category',$params);
    }
    
    /*
     * function to delete Account_cao_category
     */
    function delete_Account_cao_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_cao_category',$params);
    }
}
