<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_coa_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get Account_coa_category by id
     */
    function get_Account_coa_category($id)
    {
        return $this->db->get_where('act_coa_category',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all Account_coa_category count
     */
    function get_all_Account_coa_category_count()
    {
        $this->db->where('deleted_at',null);
        $this->db->from('act_coa_category');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all Account_coa_category
     */
    function get_all_Account_coa_category($params = array())
    {
        $this->db->where('deleted_at',null);
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('act_coa_category')->result_array();
    }
        
    /*
     * function to add new Account_coa_category
     */
    function add_Account_coa_category($params)
    {
        $this->db->insert('act_coa_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Account_coa_category
     */
    function update_Account_coa_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_coa_category',$params);
    }
    
    /*
     * function to delete Account_coa_category
     */
    function delete_Account_coa_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('act_coa_category',$params);
    }
}
