<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Department_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get department by id
     */
    function get_department($id)
    {
        return $this->db->get_where('department',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all department count
     */
    function get_all_department_count()
    {
        $this->db->from('department');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all department
     */
    function get_all_department($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('department')->result_array();
    }
        
    /*
     * function to add new department
     */
    function add_department($params)
    {
        $this->db->insert('department',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update department
     */
    function update_department($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('department',$params);
    }
    
    /*
     * function to delete department
     */
    function delete_department($id)
    {
        return $this->db->delete('department',array('id'=>$id));
    }
}
