<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_termination_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee_termination by id
     */
    function get_employee_termination($id)
    {
        return $this->db->get_where('employee_termination',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all employee_termination
     */
    function get_all_employee_termination()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->select("employee_termination.*, employees.empName, employees.empId")
                        ->from('employee_termination')
                        ->join("employees", "employees.id = employee_termination.employee_id")
                        ->get()->result_array();

        //$this->db->order_by('id', 'desc');
        //return $this->db->get('employee_termination')->result_array();
    }
        
    /*
     * function to add new employee_termination
     */
    function add_employee_termination($params)
    {
        $this->db->insert('employee_termination',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee_termination
     */
    function update_employee_termination($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee_termination',$params);
    }
    
    /*
     * function to delete employee_termination
     */
    function delete_employee_termination($id)
    {
        return $this->db->delete('employee_termination',array('id'=>$id));
    }
}
