<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_appriasal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee_appriasal by id
     */
    function get_employee_appriasal($id)
    {
        return $this->db->get_where('employee_appriasal',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all employee_appriasal count
     */
    function get_all_employee_appriasal_count()
    {
        $this->db->from('employee_appriasal');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all employee_appriasal
     */
    function get_all_employee_appriasal($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('employee_appriasal')->result_array();
    }
        
    /*
     * function to add new employee_appriasal
     */
    function add_employee_appriasal($params)
    {
        $this->db->insert('employee_appriasal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee_appriasal
     */
    function update_employee_appriasal($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee_appriasal',$params);
    }
    
    /*
     * function to delete employee_appriasal
     */
    function delete_employee_appriasal($id)
    {
        return $this->db->delete('employee_appriasal',array('id'=>$id));
    }
}
