<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_resign_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee_resign by id
     */
    function get_employee_resign($id)
    {
        return $this->db->get_where('employee_resign',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all employee_resign
     */
    function get_all_employee_resign()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->select("employee_resign.*, employees.empName, employees.empId")
                        ->from('employee_resign')
                        ->join("employees", "employees.id = employee_resign.employee_id")
                        ->get()->result_array();
       
    }
        
    /*
     * function to add new employee_resign
     */
    function add_employee_resign($params)
    {
        $this->db->insert('employee_resign',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee_resign
     */
    function update_employee_resign($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee_resign',$params);
    }
    
    /*
     * function to delete employee_resign
     */
    function delete_employee_resign($id)
    {
        return $this->db->delete('employee_resign',array('id'=>$id));
    }
}
