<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employees_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get joining_form by id
     */
    function get_employee($id)
    {
        return $this->db->get_where('employees',array('id'=>$id))->row_array();
    }

    function get_employee_empid($id)
    {
        return $this->db->get_where('employees',array('empId'=>$id))->row_array();
    }

    function get_employee_family($id)
    {
        return $this->db->get_where('emp_family_details',array('empId'=>$id))->result_array();
    }

    function get_father($id)
    {
        $result =  $this->db->select('fullName')->get_where('emp_family_details',array('empId'=>$id,'relation'=> 'Father'))->row_array();
        return $result['fullName'];
    }
    
    function get_employee_education($id)
    {
        return $this->db->get_where('emp_education',array('empId'=>$id))->result_array();
    }
    /*
     * Get all employees count
     */
    function get_all_employee_count()
    {
        $this->db->from('employees');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all employees
     */
    function get_all_employee($params = array())
    {
        $this->db->select("e.*, des.name as designation, dep.name as department");
        $this->db->join("designation as des", "des.id= e.Designation");
        $this->db->join("department as dep", "dep.id= e.Department ");
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('employees as e')->result_array();
    }

    function get_all_employee_order_dep($params = array())
    {
        $this->db->select("e.*, des.name as designation, dep.name as department");
        $this->db->join("designation as des", "des.id= e.Designation");
        $this->db->join("department as dep", "dep.id= e.Department ");
        $this->db->order_by('e.Department', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('employees as e')->result_array();
    }
        
    /*
     * function to add new employees
     */
    function add_employee($params)
    {
        $this->db->insert('employees',$params);
        return $this->db->insert_id();
    }
        
    function add_employee_family($params)
    {
        $this->db->insert_batch('emp_family_details',$params);
        //return $this->db->insert_id();
    }

    
    function add_employee_education($params)
    {
        $this->db->insert_batch('emp_education',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update employees
     */
    function update_employee($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employees',$params);
    }

    
    /*
     * function to delete employees
     */
    function delete_employee($id)
    {
        return $this->db->delete('employees',array('id'=>$id));
    }

    function delete_employee_family_empid($id)
    {
        return $this->db->delete('emp_family_details',array('empId'=>$id));
    }

    function delete_employee_education($id)
    {
        return $this->db->delete('emp_education',array('empId'=>$id));
    }

    function get_empid()
    {
        $last = $this->db->select('empId')
                        ->order_by('id',"desc")
		                ->limit(1)
                        ->get('employees')
                        ->row();
        $id=substr($last->empId, 5);
       // $ID $id+1;
        return $final_append="KRISP".++$id;
        
    }

    function add_increament($params)
    {
        $this->db->insert('increament_letters',$params);
        return $this->db->insert_id();
    }

    function get_all_increament_count()
    {
        $this->db->from('increament_letters');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all increament
     */
    function get_all_increament($params = array())
    {
        
        /* if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return  */
        $this->db->select('i.*, e.empId, e.empName');
        $this->db->join('employees e','e.id=i.employee_id');
        $this->db->order_by('id', 'desc');
       return $this->db->get('increament_letters i')->result_array();
    }

    function delete_increment($id){
        return $this->db->delete('increament_letters',array('id'=>$id));
    }

    //appraisals
    function add_appraisal($params)
    {
        $this->db->insert('appraisals',$params);
        return $this->db->insert_id();
    }

    function get_all_appraisal_count()
    {
        $this->db->from('appraisals');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all appraisal
     */
    function get_all_appraisal($params = array())
    {
        
        /* if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return  */
        $this->db->select('i.*, e.empId, e.empName');
        $this->db->join('employees e','e.id=i.employee_id');
        $this->db->order_by('id', 'desc');
       return $this->db->get('appraisals i')->result_array();
    }

    function delete_appraisal($id){
        return $this->db->delete('appraisals',array('id'=>$id));
    }
}
