<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Holiday_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get holiday by id
     */
    function get_holiday($id)
    {
        return $this->db->get_where('holidays',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all holidays
     */
    function get_all_holidays()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('holidays')->result_array();
    }
        
    /*
     * function to add new holiday
     */
    function add_holiday($params)
    {
        $this->db->insert('holidays',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update holiday
     */
    function update_holiday($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('holidays',$params);
    }
    
    /*
     * function to delete holiday
     */
    function delete_holiday($id)
    {
        return $this->db->delete('holidays',array('id'=>$id));
    }
}
