<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Leave_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get leave_type by id
     */
    function get_leave_type($id)
    {
        return $this->db->get_where('leave_type',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all leave_type
     */
    function get_all_leave_type()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('leave_type')->result_array();
    }
        
    /*
     * function to add new leave_type
     */
    function add_leave_type($params)
    {
        $this->db->insert('leave_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update leave_type
     */
    function update_leave_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('leave_type',$params);
    }
    
    /*
     * function to delete leave_type
     */
    function delete_leave_type($id)
    {
        return $this->db->delete('leave_type',array('id'=>$id));
    }
}
