<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class MOM_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mom by id
     */
    function get_mom($id)
    {
        return $this->db->get_where('mom',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all mom count
     */
    function get_all_mom_count()
    {
        $this->db->from('mom');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all mom
     */
    function get_all_mom($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('mom')->result_array();
    }

    function get_all_mom_employees($id)
    {
        return $this->db->where('mom_id',$id)->get('mom_members')->result_array();
    }
        
    /*
     * function to add new mom
     */
    function add_mom($params)
    {
        $this->db->insert('mom',$params);
        return $this->db->insert_id();
    }
    function add_employees($params)
    {
        $this->db->insert_batch('mom_members',$params);
    }
    /*
     * function to update mom
     */
    function update_mom($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('mom',$params);
    }
    
    /*
     * function to delete mom
     */
    function delete_mom($id)
    {
        return $this->db->delete('mom',array('id'=>$id));
    }
}
