<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class SiteVisit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get SiteVisit by id
     */
    function get_SiteVisit($id)
    {
        // $this->db->where('project_id',$id);
        // print_r($this->db->get('prj_site_visit')->row_array());
        return $this->db->get_where('prj_site_visit',array('id'=>$id))->row_array();
    }
    function get_name($id){
        $this->db->where('id',$id);
        $this->db->select('name');
        $this->db->from('prj_list');
        $query= $this->db->get();
        return (get_object_vars($query->result()[0])['name']);
    }
    function get_empname($id){
        $this->db->where('id',$id);
        $this->db->select('empName');
        $this->db->from('employees');
        $query= $this->db->get();
        return (get_object_vars($query->result()[0])['empName']);
    }

    /*
     * Get all SiteVisit count
     */
    function get_all_SiteVisit_count()
    {
        $this->db->from('prj_site_visit');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all SiteVisit
     */
    function get_all_SiteVisit($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->where('t1.delete_status', '0');
        $this->db->select('t1.*, t2.name as project_name,e.empName');    
        $this->db->from('prj_site_visit as t1');
        $this->db->join('prj_list as t2', 't1.project_id = t2.id');
        $this->db->join('employees as e','t1.site_engineer_id = e.id');

        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new SiteVisit
     */
    function add_SiteVisit($params)
    {
        $this->db->insert('prj_site_visit',$params);
        return $this->db->insert_id();
    }
    public function select()  
      {  
		$this->db->select("id,name");
		$this->db->from('prj_list'); 
        $query = $this->db->get();
		return $query->result();
	  }  
	  public function selectEmp()  
      {  
		$this->db->select("id,empName");
		$this->db->from('employees'); 
		$query1 = $this->db->get();
		return $query1->result();
	  }  
    
    /*
     * function to update SiteVisit
     */
    function update_SiteVisit($id,$params)
    {
        $this->db->where('id',$id);
        return($this->db->update('prj_site_visit',$params));
    }
    
    /*
     * function to delete SiteVisit
     */
    function delete_SiteVisit($id)
    {
        $this->db->where('id',$id);
        return $this->db->update('prj_site_visit',array('delete_status' => '1'));
    }
}