<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Visitor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get visitor by id
     */
    function get_visitor($id)
    {
        return $this->db->get_where('visitors',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all visitors
     */
    function get_all_visitors()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('visitors')->result_array();
    }
        
    /*
     * function to add new visitor
     */
    function add_visitor($params)
    {
        $this->db->insert('visitors',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update visitor
     */
    function update_visitor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('visitors',$params);
    }
    
    /*
     * function to delete visitor
     */
    function delete_visitor($id)
    {
        return $this->db->delete('visitors',array('id'=>$id));
    }
}
